#!/usr/bin/env bash

set -e

# Clean output
rm -rf dist

# Build project
tsc

# Copy static files
mkdir -p dist/static
cp src/static/{favicon.ico,index.html} dist/static/

# Copy chess engine
mkdir -p dist/scripts/chess/bin
cp scripts/chess/bin/chess dist/scripts/chess/bin/chess
chmod +x dist/scripts/chess/bin/chess

# Show result
tree -a dist
